### PR TITLE
remove machine-learning dockerfiles

### PR DESCRIPTION
**Pull request by liujianjunhq**
remove machine-learning and machine-learning-ui as
they are similar to clearlinux/tensorflow and
stack/DLRS.

Signed-off-by: Liu, Jianjun <jianjun.liu@intel.com>

### CODE REVIEW

**Comment by gtkramer** [comment]
It looks like we've done our due diligence to check for users, and it appears safe to remove these images.  However, I'd like to defer this decision to @bryteise for final signoff since removal is more sensitive than adding.

**Comment by ZhongbaoShi** [comment]
@bryteise , what's your opinion for this remove?

**Comment by bryteise** [comment]
Hrm seems like the content is different and the use case for machine-learning-ui is quite different from say the tensorflow image. Removing machine-learning is probably fine but I'd like to see the machine-learning-ui instead updated to be a nice Dockerfile with a service running on a port forwarded to the host that can be used to interact with a Jupiter notebook.

**Comment by liujianjunhq** [comment]
@bryteise Thanks a lot. Will remove machine-learning only, and keep machine-learning-ui updating.

**Pull request closed without merging**
