### PR TITLE
Updating name of reference stack

### PR DESCRIPTION
**Pull request by bd-dean**

### CODE REVIEW

**Comment by bryteise** [comment]
This has conflicts that need to be fixed, please rebase on latest master.

**Comment by bryteise** [comment]
@bd-dean I am still seeing patch conflicts.

**Comment by bd-dean** [comment]
> @bd-dean I am still seeing patch conflicts.

Can you tell me which files?  I get no feedback -- The UI message is "This branch has no conflicts with the base branch"

**Comment by bryteise** [comment]
Closing with #52

**Pull request closed without merging**
