### PR TITLE
Update stacks project name to align with the launch

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
@lsandoval @Dnplas can you review this change?

@bryteise i am guessing this will mean we need to flush the images we have and swap it out? both here and the release documents?

**Comment by bryteise** [comment]
@ganeshmaharaj Ugh yes, this sucks a bit. A certain devops person is going to deserve extra cookies.

**Comment by ganeshmaharaj** [comment]
@bryteise more than extra cookies. :) i am also trying to figure out when this change should land, given that there are other locations where these images are referenced. i will make sure i add you to the thread before we land this and get it moved through the cycles.

**Comment by ganeshmaharaj** [comment]
patch rebased to latest master to accomodate all name changes.

**Comment by ganeshmaharaj** [comment]
@bryteise aaahhh.. sorry i think we might need to revert this patch. Let me confirm things asap.

**Comment by ganeshmaharaj** [comment]
@bryteise this change will not affect what is available in the docker hub now correct? just making sure we aren't breaking anything for now.

**Comment by bryteise** [comment]
@ganeshmaharaj Not at the moment, we are still in manual push mode.

**Comment by ganeshmaharaj** [comment]
Perfect. I think we are good for now. I will sync up offline on the
switch-over.

Thanks,
Ganesh

**Comment by lsandoval** [comment]
@ganeshmaharaj PR merged but doing a git-grep, I still see the following:

git grep -i dlaas
WARNING: terminal is not fully functional
-  (press RETURN)
stacks/dlrs/kubeflow/dlrs-tfjob/dlrs-bench/parts.yaml:description: Prototypes for running DLaaS benchmarking on a multi node cluster
stacks/dlrs/kubeflow/dlrs-tfjob/dlrs-bench/prototypes/dlrs-alexnet.jsonnet:// @shortDescription A multi-node DLaaS benchmark
stacks/dlrs/kubeflow/dlrs-tfjob/dlrs-bench/prototypes/dlrs-resnet50.jsonnet:// @shortDescription A multi-node DLaaS benchmark
stacks/dlrs/releasenote.md: * Pull from the [Eigen version](https://hub.docker.com/r/clearlinux/stacks-dlaas-oss/)
stacks/dlrs/releasenote.md: * Pull from the [Intel MKL-DNN version](https://hub.docker.com/r/clearlinux/stacks-dlaas-mkl/)
stacks/dlrs/releasenote.md:Please refer to the [Deep Learning tutorial](https://clearlinux.org/documentation/clear-linux/tutorials/dlaas.rst) for detailed instructions for running the TensorFlow and Kubeflow Benchmarks on the docker images.
stacks/dlrs/releasenote.md:Example: For Intel® Xeon® Gold 6140 CPU @ 2.30GHz based systems with 2 Sockets and 18 Cores/Socket, 2-node distributed MKL dstraining with 1 worker per node and 1 Parameter Server (PS) can be specified and launched with this [TFJob](https://github.com/clearlinux/dockerfiles/blob/master/stacks/dlaas/kubeflow/dlaas-tfjob/dlaas-bench/prototypes/dlaas-resnet50.jsonnet)

**Pull request merged**
