### PR TITLE
add wordpress container

### PR DESCRIPTION
**Pull request by sophia0328**
Signed-off-by: Gong Sophia <sophia.gong@intel.com>

### CODE REVIEW

**Comment by rustylynch** [comment]
I am surprised to see that we are able to successfully use swupd without doing a multistage build.  Why is it that php-fpm has included os-core-update via a multistage build?  This kind of defeats the entire point of doing a multistage build, right?

**Comment by rustylynch** [comment]
Its's not a huge savings, but by removing os-core-update from clearlinux/php-fpm and then using a multistage build on clearlinux/wordpress, i end up saving 20M.

FROM clearlinux:latest AS builder
MAINTAINER sophia.gong@intel.com

ARG swupd_args

RUN swupd bundle-add curl --no-boot-update $swupd_args
RUN set -ex \
        && { \
              	cd /; \
                curl -O https://wordpress.org/latest.tar.gz; \
		tar xzvf latest.tar.gz; \
        }

FROM clearlinux/php-fpm
MAINTAINER sophia.gong@intel.com

RUN set -ex \
	&& { \
              	useradd -U www-data; \
		chown -R www-data:www-data /var/www/html; \
		chmod 777 /var/www/html; \
	}

COPY --from=builder /wordpress/ /var/www/html

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php-fpm"]

**Comment by liujianjunhq** [comment]
@rustylynch 
For containers, such as: php-fpm, php and python, they provide a language environment for developing and adding further features. As os-core-update is always needed to add new packages and bundles, just include the os-core-update bundle in these containers. 
The os-core-update is included via a mutistage build as it could keep the containers the same clearlinux version as clearlinux/os-core, and reduce the extra size because of duplicate files of os-core-update when "swupd update" if the base is clearlinux:latest.

**Comment by sophia0328** [comment]
@rustylynch, @liujianjunhq  thanks for you comments. 
 Re-submit wordpress container at https://github.com/clearlinux/dockerfiles/pull/182, please take a review.

**Pull request closed without merging**
