### PR TITLE
updating dlrs tf-mkl-dnn dockerfile

### PR DESCRIPTION
**Pull request by rahulunair**

### CODE REVIEW

**Comment by gtkramer** [comment]
@rahulunair can you try experimenting with reducing the number of run statements?  This may help bring down the size of the image by reducing the number of layers.  Rathe than `RUN`, maybe try using `&&` to chain shell commands together?

**Comment by rahulunair** [comment]
The rest of the details (release notes and env scripts) are in the patch: #115

**Comment by rahulunair** [comment]
@gtkramer this dockerfile is an exact copy of the one we have in our local from which the images that are going to be released as of V3 are based, ideally we would like to not make any changes to the file so that there is a 1:1 parity between the validated image and the dockerfile. 

If we make changes to the file, we are required to go through a full on validation and PnP verification as this a major release.

**Comment by gtkramer** [comment]
@rahulunair ah, yes, I was just thinking that.  Something to maybe try for the next iteration then :)  I'll go ahead and merge this.

**Pull request merged**
