### PR TITLE
add haproxy container

### PR DESCRIPTION
**Pull request by sophia0328**
Signed-off-by: Gong Sophia <sophia.gong@intel.com>

### CODE REVIEW

**Comment by gtkramer** [comment]
@sophia0328 overall, this looks good.  Can you please rebase to fix a couple of broken links?

**Comment by phmccarty** [comment]
@gtkramer Only the swupd link appears to be broken in this case, right?

@sophia0328 See #104 for the new link to use for swupd options.

**Comment by gtkramer** [comment]
@phmccarty ah, yes, only the swupd link is broken

**Comment by gtkramer** [comment]
@sophia0328 Please also modify .travis.yml to add haproxy to the DOCKERFILES_DIR list.

**Comment by sophia0328** [comment]
@gtkramer @phmccarty thanks for your comments. please check [https://github.com/clearlinux/dockerfiles/pull/107](# 107) for new update.

**Pull request closed without merging**
