### PR TITLE
add python env

### PR DESCRIPTION
**Pull request by sophia0328**
Signed-off-by: Gong Sophia <sophia.gong@intel.com>

### CODE REVIEW

**Comment by bryteise** [comment]
What was the purpose for adding these variables? I'm a little worried that the version in particular is not tied to content but just another place that we'll need to update a hard coded string later on.

**Comment by sophia0328** [comment]
Hi, William

We are going to add these python environment to trace the docker container name and version information.

For python version, the official web releases it as a three sub-section serial number (such as A.B.C, A to trace the big version, B to indicate the function upgrade and C for bug fix.) and upgrades the B more than a year once (for e.g: python 3.6.0 is released on Dec-23-2016, python 3.7.0 on June-27-2018, python 3.8.0 on Oct-14-2019), as the upgrade frequency is not fast, we hard code the version and will update it manually  in docker container.

Thanks,
Sophia

**Comment by qzheng527** [comment]
@sophia0328 Now we already had the tag for each container image, users could get the version from the tag. And the Clear is in the process to update to python 3.8, which will happen soon. I think we can pending the version variable for now.

**Comment by sophia0328** [comment]
@qzheng527 ok. we will trace python version by tag. 
update the patch at https://github.com/clearlinux/dockerfiles/pull/317. please take a review.

**Pull request closed without merging**
